"""
csar_workflows.py
=================
Config-driven workflows for affinity ranking of fluorinated ligands by 19F NMR,
implementing the CSAR and FastCSAR methods described in:

    Rüdisser et al., J. Biomol. NMR 74, 579–594 (2020).
    https://doi.org/10.1007/s10858-020-00325-x

Four workflows are available, selected by the ``[workflow]`` section of a TOML
configuration file:

    csar        – two-field spin-lock pipeline (full CSAR)
    fastcsar    – single-field simplified ranking (FastCSAR)
    reporter    – displacement of a known reporter ligand
    titration   – exchange-suppressed ligand-observed titration

Usage
-----
    python csar_workflows.py experiment.toml

or from Python::

    from csar_workflows import run_from_config
    results = run_from_config("experiment.toml")

Config file format
------------------
See ``example_config.toml`` (generated by running this script without arguments).
"""

from __future__ import annotations

import re
import sys
import tomllib
import warnings
from dataclasses import dataclass, field
from pathlib import Path
from typing import Dict, List, Optional, Tuple

import numpy as np
from scipy.optimize import curve_fit
from scipy.constants import hbar, mu_0
import matplotlib.pyplot as plt
import matplotlib.ticker as ticker

# ---------------------------------------------------------------------------
# Optional integration with the existing relaxation library
# ---------------------------------------------------------------------------
try:
    import klassez as kz
    _GAMMA = kz.sim.gamma          # dict: nucleus symbol -> MHz / T
except ImportError:
    # Fallback table (gyromagnetic ratios in MHz/T)
    _GAMMA = {"19F": 40.0774, "1H": 42.5774, "13C": 10.7084, "15N": -4.3160}


# ============================================================================
# Physical / NMR helper functions
# ============================================================================

def gamma_rad(nucleus: str) -> float:
    """Gyromagnetic ratio in rad s⁻¹ T⁻¹."""
    return _GAMMA[nucleus] * 2 * np.pi * 1e6


def spectral_density_iso(omega: float, tau: float) -> float:
    """Isotropic Lorentzian spectral density  J(ω) = τ / (1 + ω²τ²)."""
    return tau / (1.0 + (omega * tau) ** 2)


def R2_CSA_bound(
    delta_sigma_ppm: float,
    eta: float,
    B0: float,
    tau_c: float,
    nucleus: str = "19F",
) -> float:
    """
    Transverse CSA relaxation rate in the bound state (Eq. 5, Rüdisser 2020).

    Parameters
    ----------
    delta_sigma_ppm : float
        Reduced anisotropy δσ in ppm (δσ = σ_zz - σ_iso).
    eta : float
        Axial asymmetry η = (σ_yy - σ_xx) / δσ.
    B0 : float
        Magnetic field in Tesla.
    tau_c : float
        Rotational correlation time of the complex in seconds.
    nucleus : str
        NMR-active nucleus (default ``'19F'``).

    Returns
    -------
    float
        R₂,CSA,b in s⁻¹.

    Notes
    -----
    The formula uses the combined anisotropy parameter
    δσ²(1 + η²/3), which equals Δσ²(1 + η²/3)·(4/9) when converting from
    overall anisotropy Δσ.  Here we work directly with the reduced anisotropy
    δσ (= 2/3 · Δσ) as used throughout the paper.
    """
    delta_sigma = delta_sigma_ppm * 1e-6          # ppm → dimensionless
    gF = gamma_rad(nucleus)
    omegaF = gF * B0
    J0   = spectral_density_iso(0.0,    tau_c)
    JomF = spectral_density_iso(omegaF, tau_c)
    prefactor = (1.0 / 20.0) * gF**2 * B0**2 * delta_sigma**2 * (1.0 + eta**2 / 3.0)
    return prefactor * (4.0 * J0 + 3.0 * JomF)


def R2_CSA_bound_tensor(
    sigma: np.ndarray,
    B0: float,
    tau_c: float,
    nucleus: str = "19F",
) -> float:
    """
    Transverse CSA relaxation using the full 3×3 shielding tensor
    (Eqs. 18–19, Suturina et al. 2018, already used in your CSA_relaxation).

    sigma : 3×3 ndarray in ppm — will be converted to dimensionless internally.
    """
    from fun_hetrelax_models import J, J_omega_tau_iso  # type: ignore
    sigma_d = np.asarray(sigma, dtype=float) / 1e6
    gF = gamma_rad(nucleus)
    omegaF = gF * B0
    tau_params = (tau_c,)
    bigLambda2 = (
        (sigma_d[0, 1] - sigma_d[1, 0]) ** 2
        + (sigma_d[0, 2] - sigma_d[2, 0]) ** 2
        + (sigma_d[1, 2] - sigma_d[2, 1]) ** 2
    )
    bigDelta2 = (
        sigma_d[0, 0] ** 2 + sigma_d[1, 1] ** 2 + sigma_d[2, 2] ** 2
        - sigma_d[0, 0] * sigma_d[1, 1]
        - sigma_d[0, 0] * sigma_d[2, 2]
        - sigma_d[1, 1] * sigma_d[2, 2]
        + 0.75 * (
            (sigma_d[0, 1] + sigma_d[1, 0]) ** 2
            + (sigma_d[0, 2] + sigma_d[2, 0]) ** 2
            + (sigma_d[1, 2] + sigma_d[2, 1]) ** 2
        )
    )
    J0   = J(J_omega_tau_iso, 0,       tau_params)
    JomF = J(J_omega_tau_iso, omegaF,  tau_params)
    J3omF= J(J_omega_tau_iso, 3*omegaF,tau_params)
    R2 = (
        (5.0 / 24.0) * omegaF**2 * bigLambda2 * J3omF
        + (1.0 / 18.0) * omegaF**2 * bigDelta2 * (4.0 * J0 + 3.0 * JomF)
    )
    return R2


def fit_monoexponential(delays: np.ndarray, intensities: np.ndarray) -> Tuple[float, float]:
    """
    Fit I(t) = I0 · exp(−R2 · t) and return (R2, I0).

    Parameters
    ----------
    delays : array-like
        Relaxation delays in seconds.
    intensities : array-like
        Corresponding signal intensities (arbitrary units, positive).

    Returns
    -------
    R2 : float
        Fitted relaxation rate in s⁻¹.
    I0 : float
        Fitted initial intensity.
    """
    delays = np.asarray(delays, dtype=float)
    intensities = np.asarray(intensities, dtype=float)
    def model(t, I0, R2):
        return I0 * np.exp(-R2 * t)
    p0 = (intensities[0], 1.0 / delays[-1])
    popt, _ = curve_fit(model, delays, intensities, p0=p0, maxfev=5000)
    return float(popt[1]), float(popt[0])


# ============================================================================
# Data containers
# ============================================================================

@dataclass
class CompoundData:
    """All per-compound information needed across workflows."""
    name: str
    fluorine_type: str          # 'CF3' or 'CF'
    # CSA parameters (reduced anisotropy and asymmetry, as in Fig. 2)
    delta_sigma: float          # ppm
    eta: float
    # Relaxation data: dict mapping field (T) -> (delays_s, intensities_free, intensities_protein)
    relaxation_data: Dict[float, Tuple[np.ndarray, np.ndarray, np.ndarray]] = field(default_factory=dict)
    # Pre-fitted R2 values: dict mapping field -> (R2_free, R2_protein)
    R2_fitted: Dict[float, Tuple[float, float]] = field(default_factory=dict)
    # 1σ uncertainties on R2_fitted, same keys: (σ_R2_free, σ_R2_protein)
    # nan entries mean the uncertainty was not estimated.
    R2_err: Dict[float, Tuple[float, float]] = field(default_factory=dict)
    # For reporter workflow: reporter signal intensity (−protein, +protein)
    reporter_signal_minus: Optional[float] = None
    reporter_signal_plus: Optional[float] = None


@dataclass
class WorkflowResult:
    """Unified output from any workflow."""
    workflow: str
    compound_names: List[str]
    scores: np.ndarray          # higher = stronger binder
    pb_estimates: Optional[np.ndarray] = None
    pb_uncertainties: Optional[np.ndarray] = None  # 1σ on p_b, same order as scores
    KD_estimates: Optional[np.ndarray] = None   # µM, if available
    R2_raw: Optional[Dict] = None
    notes: List[str] = field(default_factory=list)


# ============================================================================
# Workflow 1: CSAR (two-field spin-lock, full pipeline)
# ============================================================================

def workflow_CSAR(
    compounds: List[CompoundData],
    B_high: float,
    B_low: float,
    tau_c: float,
    nucleus: str = "19F",
    protein_MW_kDa: float = 23.0,
) -> WorkflowResult:
    """
    Full CSAR pipeline (Section "Results", Rüdisser 2020).

    Steps
    -----
    1. Obtain R₂ at two fields under spin-lock (exchange suppressed).
    2. Subtract low-field from high-field → ΔR₂ ≈ p_b · 0.49 · R₂,CSA,b,high
       (Eqs. 7–8; the factor 0.49 = 1 − (B_low/B_high)² for the two fields
       11.75 T and 16.4 T used in the paper; generalised here).
    3. Divide ΔR₂ by the calculated Δ(R₂,CSA,b) to get p_b.

    Parameters
    ----------
    compounds : list of CompoundData
        Each compound must have R2_fitted populated for both B_high and B_low.
    B_high, B_low : float
        Magnetic fields in Tesla.
    tau_c : float
        Rotational correlation time of the protein–ligand complex (s).
    nucleus : str
        Observed nucleus.
    protein_MW_kDa : float
        Protein molecular weight, used only for documentation / RDD estimate.

    Returns
    -------
    WorkflowResult
    """
    names, pb_list, sigma_pb_list = [], [], []
    dR2_obs_list, R2CSA_calc_list = [], []

    # ΔR₂,CSA,b = R₂,CSA,b(high) − R₂,CSA,b(low)  (Eq. 8)
    # ≈ R₂,CSA,b(high) · (1 − (B_low/B_high)²)    by B² scaling
    field_ratio_sq = (B_low / B_high) ** 2

    notes = []
    for c in compounds:
        if B_high not in c.R2_fitted or B_low not in c.R2_fitted:
            warnings.warn(f"Compound {c.name}: missing R2 data for one or both fields — skipping.")
            continue

        R2_f_high, R2_p_high = c.R2_fitted[B_high]
        R2_f_low,  R2_p_low  = c.R2_fitted[B_low]

        # Step 1: subtract free-ligand contribution (Eq. 7 full form)
        dR2_obs = (R2_p_high - R2_f_high) - (R2_p_low - R2_f_low)

        # Step 2: calculate R₂,CSA,b at high field
        R2CSA_high = R2_CSA_bound(c.delta_sigma, c.eta, B_high, tau_c, nucleus)
        dR2CSA_calc = R2CSA_high * (1.0 - field_ratio_sq)

        # Step 3: p_b estimate (Eq. 9)
        if dR2CSA_calc <= 0:
            warnings.warn(f"Compound {c.name}: calculated ΔR₂,CSA ≤ 0 — check tensor parameters.")
            pb = 0.0
        else:
            pb = max(dR2_obs / dR2CSA_calc, 0.0)

        # Uncertainty propagation (Eq. 7): ΔR₂ = ΔR₂_high - ΔR₂_low
        #   σ²_ΔR₂ = σ²_p_high + σ²_f_high + σ²_p_low + σ²_f_low
        #   σ_p_b  = σ_ΔR₂ / ΔR₂_CSA_calc  (calculated CSA has no fit uncertainty)
        err_high  = c.R2_err.get(B_high, (np.nan, np.nan))
        err_low   = c.R2_err.get(B_low,  (np.nan, np.nan))
        err_terms = [err_high[1], err_high[0], err_low[1], err_low[0]]
        if all(not np.isfinite(e) for e in err_terms):
            sigma_dR2 = np.nan     # no errors available for this compound
        else:
            sigma_dR2 = np.sqrt(np.nansum([e**2 for e in err_terms]))
        sigma_pb = (sigma_dR2 / dR2CSA_calc
                    if (dR2CSA_calc > 0 and np.isfinite(sigma_dR2))
                    else np.nan)

        names.append(c.name)
        pb_list.append(pb)
        sigma_pb_list.append(sigma_pb)
        dR2_obs_list.append(dR2_obs)
        R2CSA_calc_list.append(dR2CSA_calc)

    pb_arr = np.array(pb_list)
    if len(pb_arr) == 0:
        raise ValueError("No compounds with data at both fields. Check R2_fitted keys.")
    # Normalise to [0, 1] relative to the strongest binder for ranking
    pb_max = pb_arr.max() if pb_arr.max() > 0 else 1.0
    scores = pb_arr / pb_max

    notes.append(
        f"B_high={B_high} T, B_low={B_low} T, τ_c={tau_c:.2e} s; "
        f"field factor (1−(B_low/B_high)²) = {1-field_ratio_sq:.4f}"
    )

    sigma_pb_arr = np.array(sigma_pb_list)
    return WorkflowResult(
        workflow="CSAR",
        compound_names=names,
        scores=scores,
        pb_estimates=pb_arr,
        pb_uncertainties=sigma_pb_arr / pb_max,   # normalised like scores
        R2_raw={"dR2_obs": dR2_obs_list, "dR2CSA_calc": R2CSA_calc_list,
                "sigma_dR2": sigma_pb_list},
        notes=notes,
    )


# ============================================================================
# Workflow 2: FastCSAR (single-field, Eq. 11)
# ============================================================================

def workflow_FastCSAR(
    compounds: List[CompoundData],
    B: float,
    tau_c: float,
    t_short: float,
    t_long: float,
    nucleus: str = "19F",
    protein_MW_kDa: float = 23.0,
) -> WorkflowResult:
    """
    Simplified FastCSAR ranking (Eq. 11, Rüdisser 2020).

    Uses two time-points from a single spin-lock experiment at one field.
    Signal decay ratio corrected for free-ligand relaxation and normalised
    by calculated R₂,b = R₂,DD,b + R₂,CSA,b.

    Parameters
    ----------
    compounds : list of CompoundData
        Each compound must have relaxation_data populated for field B with
        arrays of at least two delays that bracket t_short and t_long, OR
        have R2_fitted[B] populated directly (in which case t_short/t_long
        are used only to compute the effective decay ratio analytically).
    B : float
        Magnetic field in Tesla.
    tau_c : float
        Rotational correlation time of the complex (s).
    t_short, t_long : float
        Two spin-lock delays in seconds used to estimate signal decay.
        Typically 5 ms and 200 ms (CF₃) or 100 ms (CF).
    nucleus : str
        Observed nucleus.
    protein_MW_kDa : float
        Protein molecular weight (kDa) — used to estimate R₂,DD,b via the
        rule-of-thumb R_DD ≈ MW [kDa⁻¹ s⁻¹] (paper's approximation).

    Returns
    -------
    WorkflowResult
    """
    # Rule-of-thumb dipolar contribution (bound state, paper p. 586)
    R2_DD_b = protein_MW_kDa          # s⁻¹ · kDa⁻¹ · kDa = s⁻¹

    names, pb_list, sigma_pb_list = [], [], []
    notes = []

    for c in compounds:
        # --- get I(t_short) and I(t_long) in the presence and absence of protein
        sigma_lnterm = np.nan   # propagated fit uncertainty on the log-ratio
        if B in c.relaxation_data:
            delays, I_free, I_prot = c.relaxation_data[B]
            delays = np.asarray(delays)
            I_free = np.asarray(I_free)
            I_prot = np.asarray(I_prot)
            # Interpolate or find nearest time-points
            idx_s = int(np.argmin(np.abs(delays - t_short)))
            idx_l = int(np.argmin(np.abs(delays - t_long)))
            It_free_s = I_free[idx_s]; It_free_l = I_free[idx_l]
            It_prot_s = I_prot[idx_s]; It_prot_l = I_prot[idx_l]
            I0_free = I_free[0];      I0_prot = I_prot[0]
            # Use long time-point as described in the paper
            # ln(I(t)_p/I(0)_p  /  I(t)_f/I(0)_f) / (R2_b · t)
            ratio_p = It_prot_l / I0_prot if I0_prot > 0 else 1e-9
            ratio_f = It_free_l / I0_free if I0_free > 0 else 1e-9
            lnterm = np.log(max(ratio_p / ratio_f, 1e-9))
        elif B in c.R2_fitted and isinstance(c.R2_fitted[B], tuple):
            # Analytical path: simulate signal decay ratio from fitted R2 values.
            # ln(I(t)_p/I(0)_p / I(t)_f/I(0)_f) = -(R2_prot - R2_free) * t  (negative)
            R2_free, R2_prot = c.R2_fitted[B]
            lnterm = -(R2_prot - R2_free) * t_long   # negative → p_b positive after negation
            # σ_lnterm = t_long × √(σ_R2_prot² + σ_R2_free²)
            err = c.R2_err.get(B, (np.nan, np.nan))
            err_terms_fc = [err[1], err[0]]  # [σ_prot, σ_free]
            if all(not np.isfinite(e) for e in err_terms_fc):
                sigma_lnterm = np.nan
            else:
                sigma_lnterm = t_long * np.sqrt(np.nansum([e**2 for e in err_terms_fc]))
        else:
            warnings.warn(f"Compound {c.name}: no data at B={B} T — skipping.")
            continue

        # R₂,b = R₂,DD,b + R₂,CSA,b  (Eq. 5 + rule of thumb)
        R2_CSA_b = R2_CSA_bound(c.delta_sigma, c.eta, B, tau_c, nucleus)
        R2_b = R2_DD_b + R2_CSA_b

        t_eff = t_long
        # lnterm is negative (signal decays), so negate to get positive p_b (Eq. 11)
        pb = -lnterm / (R2_b * t_eff) if (R2_b * t_eff) != 0 else 0.0
        pb = max(pb, 0.0)
        # σ_p_b = σ_lnterm / (R2_b × t_long)
        sigma_pb = (sigma_lnterm / (R2_b * t_eff)
                    if (np.isfinite(sigma_lnterm) and R2_b * t_eff != 0)
                    else np.nan)

        names.append(c.name)
        pb_list.append(pb)
        sigma_pb_list.append(sigma_pb)

    pb_arr = np.array(pb_list)
    pb_max = pb_arr.max() if pb_arr.max() > 0 else 1.0
    scores = pb_arr / pb_max

    notes.append(
        f"B={B} T, τ_c={tau_c:.2e} s, t_long={t_long*1e3:.0f} ms, "
        f"R₂,DD,b ≈ {R2_DD_b:.1f} s⁻¹ (MW rule-of-thumb)"
    )

    sigma_pb_arr = np.array(sigma_pb_list)
    return WorkflowResult(
        workflow="FastCSAR",
        compound_names=names,
        scores=scores,
        pb_estimates=pb_arr,
        pb_uncertainties=sigma_pb_arr / pb_max,
        notes=notes,
    )


# ============================================================================
# Workflow 3: Reporter assay
# ============================================================================

def workflow_reporter(
    reporter_name: str,
    reporter_signal_free: float,
    reporter_signal_protein: float,
    compounds: List[CompoundData],
) -> WorkflowResult:
    """
    Reporter assay affinity ranking (Fig. 7, Rüdisser 2020).

    The reporter signal is measured in the presence of each test compound.
    Displacement of the reporter is proportional to relative binding affinity.

    Parameters
    ----------
    reporter_name : str
        Name of the reporter ligand.
    reporter_signal_free : float
        Intensity of the reporter signal WITHOUT protein.
    reporter_signal_protein : float
        Intensity of the reporter signal WITH protein (no competitor).
    compounds : list of CompoundData
        Each compound must have ``reporter_signal_plus`` set to the
        intensity of the reporter in the presence of BOTH protein and that
        compound.  ``reporter_signal_minus`` is unused here.

    Returns
    -------
    WorkflowResult
        ``scores`` encodes degree of displacement (higher = stronger binder).
    """
    # Reference: fractional reporter signal in presence of protein (no competitor)
    I_ref = reporter_signal_protein / reporter_signal_free  # ~0.2 in the paper

    names, scores_list = [], []
    for c in compounds:
        if c.reporter_signal_plus is None:
            warnings.warn(f"Compound {c.name}: reporter_signal_plus not set — skipping.")
            continue
        I_comp = c.reporter_signal_plus / reporter_signal_free
        # Displacement = how much the reporter recovers toward the free signal
        # 0 = no displacement (same as with protein only), 1 = full displacement
        displacement = max((I_comp - I_ref) / (1.0 - I_ref), 0.0)
        names.append(c.name)
        scores_list.append(displacement)

    scores = np.array(scores_list)
    s_max = scores.max() if scores.max() > 0 else 1.0

    notes = [
        f"Reporter: {reporter_name}, I_free={reporter_signal_free:.3f}, "
        f"I_protein={reporter_signal_protein:.3f} (fraction={I_ref:.3f})"
    ]
    return WorkflowResult(
        workflow="Reporter",
        compound_names=names,
        scores=scores / s_max,
        notes=notes,
    )


# ============================================================================
# Workflow 4: Exchange-suppressed ligand-observed titration (Eq. 12)
# ============================================================================

def workflow_titration(
    compounds: List[CompoundData],
    B: float,
    protein_concentrations: np.ndarray,
    ligand_concentration: float,
    tau_c: float,
    nucleus: str = "19F",
    n_sites: int = 1,
    fit_KD: bool = False,
) -> WorkflowResult:
    """
    Exchange-suppressed ligand-observed titration (Fig. 8, Rüdisser 2020).

    Each compound in ``compounds`` must have relaxation_data[B] set as a
    2-D array: rows = protein concentrations (same order as
    ``protein_concentrations``), columns = (delays, intensities).
    Alternatively, if R2_fitted[B] is a list of (R2_free, R2_prot) tuples
    per protein concentration, those are used directly.

    Parameters
    ----------
    compounds : list of CompoundData
        relaxation_data[B] should be a list of (delays, intensities) arrays,
        one per protein concentration.  Or R2_fitted[B] = list of R2 values
        at each [P].
    B : float
        Magnetic field in Tesla.
    protein_concentrations : array-like
        Protein concentrations in µM (same order as data in each compound).
    ligand_concentration : float
        Total ligand concentration in µM.
    tau_c : float
        Rotational correlation time of the complex (s).
    nucleus : str
        Observed nucleus.
    n_sites : int
        Number of equivalent binding sites (default 1).
    fit_KD : bool
        If True, attempt to fit KD from Eq. 12.  This is ill-conditioned
        for weak binders (see Discussion) — a warning is emitted.

    Returns
    -------
    WorkflowResult
        ``scores`` = slope of R₂ vs [P] (normalised).
        ``KD_estimates`` = fitted KD in µM if fit_KD=True, else None.
    """
    prot_arr = np.asarray(protein_concentrations, dtype=float)  # µM
    L_tot = ligand_concentration   # µM

    names, slopes, KD_fits = [], [], []
    notes = []

    for c in compounds:
        # Collect R2 values at each protein concentration
        if isinstance(c.R2_fitted.get(B), list):
            R2_vals = np.array([r for r in c.R2_fitted[B]], dtype=float)
        elif B in c.relaxation_data and isinstance(c.relaxation_data[B], list):
            R2_vals = []
            for delays_i, intensities_i in c.relaxation_data[B]:
                r2_i, _ = fit_monoexponential(np.asarray(delays_i), np.asarray(intensities_i))
                R2_vals.append(r2_i)
            R2_vals = np.array(R2_vals)
        else:
            warnings.warn(f"Compound {c.name}: titration data not found — skipping.")
            continue

        R2_free = R2_vals[0] if prot_arr[0] == 0.0 else R2_vals.min()

        # --- Ranking by slope (R2 / [P]) as in the paper ---
        # Use simple linear regression of R2 vs [P] for robustness
        slope, _ = np.polyfit(prot_arr, R2_vals, 1)
        names.append(c.name)
        slopes.append(slope)

        if fit_KD:
            # Eq. 12:  R2_SL = R2_f + n·[P]_tot·(R2_b − R2_f) / (KD + [L]_f) · [L]_f/[L]_tot
            # Simplified assuming [L]_f ≈ [L]_tot (p_b << 1)
            def titration_eq(P_tot, KD, R2_b):
                Lf = L_tot  # approximation
                return R2_free + n_sites * P_tot * (R2_b - R2_free) / (KD + Lf)
            try:
                popt, pcov = curve_fit(
                    titration_eq, prot_arr, R2_vals,
                    p0=[500.0, R2_free * 10],
                    bounds=([0.01, R2_free], [1e5, R2_free * 1000]),
                    maxfev=10000,
                )
                KD_fits.append(popt[0])
            except RuntimeError:
                KD_fits.append(np.nan)
                notes.append(f"KD fit did not converge for {c.name}.")

    slopes_arr = np.array(slopes)
    s_max = slopes_arr.max() if slopes_arr.max() > 0 else 1.0
    scores = slopes_arr / s_max

    if fit_KD:
        warnings.warn(
            "KD fitting from ligand-observed titrations is ill-conditioned "
            "for weak binders (large KD/R2_b co-variance). "
            "Use slope ranking as primary output.",
            UserWarning,
        )
        notes.append(
            "KD values carry large uncertainty (see Rüdisser 2020, Discussion)."
        )

    return WorkflowResult(
        workflow="Titration",
        compound_names=names,
        scores=scores,
        KD_estimates=np.array(KD_fits) if KD_fits else None,
        notes=notes,
    )


# ============================================================================
# Visualisation
# ============================================================================

def plot_ranking(result: WorkflowResult, output_path: Optional[str] = None) -> None:
    """
    Bar chart of affinity ranking from any workflow result.

    Parameters
    ----------
    result : WorkflowResult
    output_path : str, optional
        If given, save figure to this path instead of displaying.
    """
    n = len(result.compound_names)
    order = np.argsort(result.scores)[::-1]
    names_sorted  = [result.compound_names[i] for i in order]
    scores_sorted = result.scores[order]

    fig, ax = plt.subplots(figsize=(max(6, n * 0.7), 4))
    colors = plt.cm.viridis(np.linspace(0.2, 0.85, n))

    # Error bars on the normalised score axis (σ_score = σ_p_b / p_b_max)
    yerr = None
    if result.pb_uncertainties is not None:
        yerr = result.pb_uncertainties[order]
        # Cap bars so they never extend below 0
        yerr_lo = np.minimum(yerr, scores_sorted)
        yerr = np.array([yerr_lo, yerr])

    bars = ax.bar(range(n), scores_sorted, color=colors, edgecolor="white",
                  linewidth=0.8, yerr=yerr,
                  error_kw=dict(ecolor="0.3", capsize=3, linewidth=1.2))

    if result.pb_estimates is not None:
        pb_sorted = result.pb_estimates[order]
        for bar, pb in zip(bars, pb_sorted):
            ax.text(
                bar.get_x() + bar.get_width() / 2,
                bar.get_height() + 0.01,
                f"{pb*100:.1f}%",
                ha="center", va="bottom", fontsize=7, color="0.3",
            )

    if result.KD_estimates is not None:
        KD_sorted = result.KD_estimates[order]
        for bar, kd in zip(bars, KD_sorted):
            if not np.isnan(kd):
                ax.text(
                    bar.get_x() + bar.get_width() / 2,
                    bar.get_height() / 2,
                    f"KD≈{kd:.0f}µM",
                    ha="center", va="center", fontsize=6.5,
                    color="white", fontweight="bold",
                )

    ax.set_xticks(range(n))
    ax.set_xticklabels(names_sorted, rotation=40, ha="right", fontsize=9)
    ax.set_ylabel("Relative affinity (normalised score)", fontsize=9)
    ax.set_title(f"{result.workflow} affinity ranking", fontsize=11, fontweight="bold")
    ax.yaxis.set_major_formatter(ticker.PercentFormatter(xmax=1))
    ax.set_ylim(0, 1.15)
    ax.spines[["top", "right"]].set_visible(False)

    if result.notes:
        fig.text(0.01, 0.01, " | ".join(result.notes), fontsize=6, color="0.5",
                 wrap=True, va="bottom")

    fig.tight_layout(rect=[0, 0.04, 1, 1])

    if output_path:
        fig.savefig(output_path, dpi=150, bbox_inches="tight")
        print(f"[plot] Saved ranking to {output_path}")
    else:
        plt.show()
    plt.close(fig)


def print_ranking_table(result: WorkflowResult) -> None:
    """Print a formatted ranking table to stdout."""
    order = np.argsort(result.scores)[::-1]
    has_err = (result.pb_uncertainties is not None and
               np.any(np.isfinite(result.pb_uncertainties)))
    header = f"{'Rank':>4}  {'Compound':<20}  {'Score':>8}"
    if result.pb_estimates is not None:
        header += f"  {'p_b (%)':>8}"
    if has_err:
        header += f"  {'± (%)':>7}"
    if result.KD_estimates is not None:
        header += f"  {'KD (µM)':>10}"
    print(f"\n{'='*len(header)}")
    print(f"  {result.workflow} ranking")
    print(f"{'='*len(header)}")
    print(header)
    print("-" * len(header))
    for rank, i in enumerate(order, 1):
        line = f"{rank:>4}  {result.compound_names[i]:<20}  {result.scores[i]:>8.4f}"
        if result.pb_estimates is not None:
            line += f"  {result.pb_estimates[i]*100:>7.2f}%"
        if has_err:
            sig = result.pb_uncertainties[i]
            line += f"  {sig*100:>6.2f}%" if np.isfinite(sig) else f"  {'N/A':>6}"
        if result.KD_estimates is not None:
            kd = result.KD_estimates[i]
            line += f"  {kd:>10.1f}" if not np.isnan(kd) else f"  {'N/A':>10}"
        print(line)
    print("=" * len(header))
    if result.notes:
        for note in result.notes:
            print(f"  Note: {note}")
    print()


# ============================================================================
# TOML config loader and dispatcher
# ============================================================================

def _parse_compound(name: str, cfg: dict) -> CompoundData:
    """Build a CompoundData from a ``[compound.NAME]`` config block.

    R2 values live in a ``[compound.NAME.R2]`` sub-table whose keys are the
    magnetic field strength in Tesla (as a quoted string, e.g. ``"16.4"``).
    Values are either:

    * ``[R2_free, R2_protein]``  — two-element list for CSAR / FastCSAR
    * ``[R2_0, R2_1, ...]``      — one value per protein concentration for titration

    FastCSAR can alternatively be driven off raw delay/intensity arrays
    instead of a pre-fitted R2 — those live in a separate
    ``[compound.NAME.relaxation_data]`` sub-table (as written by
    ``populate_config.py``'s fastcsar "raw" output mode), keyed the same
    way by field strength, with each entry an inline table of
    ``delays_free``, ``delays_protein``, ``intensity_free``, and
    ``intensity_protein`` arrays.
    """
    c = CompoundData(
        name=name,
        fluorine_type=cfg.get("fluorine_type", "CF3"),
        delta_sigma=float(cfg["delta_sigma"]),
        eta=float(cfg.get("eta", 0.0)),
    )
    # R2 sub-table: keys are field strengths in Tesla (strings)
    for B_str, val in cfg.get("R2", {}).items():
        B = float(B_str)
        if isinstance(val, list) and len(val) == 2:
            c.R2_fitted[B] = (float(val[0]), float(val[1]))
        elif isinstance(val, list):
            # Titration: one R2 per protein concentration
            c.R2_fitted[B] = [float(v) for v in val]
    # R2_err sub-table: 1σ uncertainties, same structure as R2
    for B_str, val in cfg.get("R2_err", {}).items():
        B = float(B_str)
        if isinstance(val, list) and len(val) >= 2:
            c.R2_err[B] = (float(val[0]), float(val[1]))
    # relaxation_data sub-table: raw delay/intensity arrays for FastCSAR's
    # point-ratio path (used when no R2 was fitted for this field). Each
    # entry stores delays_free and delays_protein separately, but
    # workflow_FastCSAR indexes I_free/I_prot off one shared `delays`
    # array (Eq. 11 assumes both conditions were sampled at the same
    # delay points), so delays_free is used as that array, falling back
    # to delays_protein if the free-ligand series is missing.
    for B_str, val in cfg.get("relaxation_data", {}).items():
        B = float(B_str)
        delays_free       = [float(x) for x in val.get("delays_free", [])]
        delays_protein    = [float(x) for x in val.get("delays_protein", [])]
        intensity_free    = [float(x) for x in val.get("intensity_free", [])]
        intensity_protein = [float(x) for x in val.get("intensity_protein", [])]
        delays = delays_free or delays_protein
        c.relaxation_data[B] = (
            np.array(delays),
            np.array(intensity_free),
            np.array(intensity_protein),
        )
    # Optional: reporter signal
    if "reporter_signal_plus" in cfg:
        c.reporter_signal_plus = float(cfg["reporter_signal_plus"])
    if "reporter_signal_minus" in cfg:
        c.reporter_signal_minus = float(cfg["reporter_signal_minus"])
    return c


def _sanitize_dirname(name: str) -> str:
    """
    Turn an arbitrary protein name into a filesystem-safe directory
    component: whitespace → underscore, anything else that isn't
    alphanumeric/underscore/hyphen stripped out.

    Must produce the *identical* string ``populate_config.py``'s own
    ``_sanitize_dirname`` produces for the same ``protein_name`` — that
    script writes each compound's per-field fit results under
    ``fit_results/{protein_name}/``, and this workflow's ranking plot
    needs to land in that same directory rather than a differently-named
    one.
    """
    safe = re.sub(r"\s+", "_", name.strip())
    safe = re.sub(r"[^A-Za-z0-9_-]", "", safe)
    return safe or "protein"


def _basedir(protein_name: Optional[str]) -> Path:
    """
    Return the ``fit_results`` directory to save the ranking plot into,
    namespaced by protein name when one is known — mirrors
    ``populate_config.py``'s ``_basedir`` exactly (see its docstring).
    Creates the directory if it doesn't exist yet.
    """
    basedir = Path("fit_results")
    if protein_name:
        basedir = basedir / _sanitize_dirname(protein_name)
    basedir.mkdir(parents=True, exist_ok=True)
    return basedir


def run_from_config(config_path: str) -> WorkflowResult:
    """
    Parse a TOML config file and run the specified workflow.

    Parameters
    ----------
    config_path : str
        Path to the ``.toml`` configuration file.

    Returns
    -------
    WorkflowResult
    """
    with open(config_path, "rb") as fh:
        cfg = tomllib.load(fh)

    wf_cfg       = cfg["workflow"]
    wf_name      = wf_cfg["name"].lower()
    nucleus      = wf_cfg.get("nucleus", "19F")
    tau_c        = float(wf_cfg.get("tau_c", 10e-9))
    MW_kDa       = float(wf_cfg.get("protein_MW_kDa", 23.0))
    plot_out     = wf_cfg.get("plot_output", None)
    protein_name = wf_cfg.get("protein_name", None)

    compounds = [
        _parse_compound(name, comp_cfg)
        for name, comp_cfg in cfg.get("compound", {}).items()
    ]

    if wf_name == "csar":
        B_high = float(wf_cfg["B_high"])
        B_low  = float(wf_cfg["B_low"])
        result = workflow_CSAR(compounds, B_high, B_low, tau_c, nucleus, MW_kDa)

    elif wf_name == "fastcsar":
        B       = float(wf_cfg["B"])
        t_short = float(wf_cfg.get("t_short", 5e-3))
        t_long  = float(wf_cfg.get("t_long", 200e-3))
        result  = workflow_FastCSAR(compounds, B, tau_c, t_short, t_long, nucleus, MW_kDa)

    elif wf_name == "reporter":
        rep_cfg  = cfg["reporter"]
        result   = workflow_reporter(
            reporter_name          = rep_cfg["name"],
            reporter_signal_free   = float(rep_cfg["signal_free"]),
            reporter_signal_protein= float(rep_cfg["signal_protein"]),
            compounds              = compounds,
        )

    elif wf_name == "titration":
        prot_conc = np.array(wf_cfg["protein_concentrations"], dtype=float)
        lig_conc  = float(wf_cfg["ligand_concentration"])
        fit_KD    = bool(wf_cfg.get("fit_KD", False))
        B         = float(wf_cfg["B"])
        result    = workflow_titration(
            compounds, B, prot_conc, lig_conc, tau_c, nucleus,
            fit_KD=fit_KD,
        )

    else:
        raise ValueError(
            f"Unknown workflow '{wf_name}'. Choose: csar, fastcsar, reporter, titration."
        )

    print_ranking_table(result)
    if plot_out:
        # Save alongside populate_config.py's per-compound fit_results/
        # {protein_name}/ figures rather than wherever the process
        # happens to be running from — same directory, same naming
        # convention, one place to look for every plot from this run.
        plot_out = _basedir(protein_name) / Path(plot_out).name
        plot_ranking(result, output_path=plot_out)
    else:
        plot_ranking(result)

    return result


# ============================================================================
# Example config generator
# ============================================================================

EXAMPLE_TOML = """\
# ============================================================
# CSAR / FastCSAR configuration file
# ============================================================
# Select workflow: csar | fastcsar | reporter | titration
# ============================================================

[workflow]
name             = "csar"          # workflow to run
nucleus          = "19F"           # observed nucleus
tau_c            = 1.0e-8          # rotational correlation time of complex (s)
protein_MW_kDa   = 23.0            # protein MW for RDD rule-of-thumb
B_high           = 16.4            # Tesla  (700 MHz 1H)
B_low            = 11.75           # Tesla  (500 MHz 1H)
plot_output      = "ranking.png"   # omit to display interactively

# ------------------------------------------------------------
# Define one [compound.NAME] block per ligand, with a nested
# [compound.NAME.R2] sub-table.  Keys in R2 are the magnetic
# field strength in Tesla (quoted strings); values are
# [R2_free, R2_protein]  (s^-1, measured under spin lock).
#
# delta_sigma : reduced anisotropy δσ (ppm)
# eta         : axial asymmetry η  (0 for CF3, non-zero for CF)
# ------------------------------------------------------------

[compound.compound_1]
fluorine_type = "CF3"
delta_sigma   = 36.7
eta           = 0.0

[compound.compound_1.R2]
"16.4"  = [0.65, 2.95]
"11.75" = [0.60, 2.02]

[compound.compound_2]
fluorine_type = "CF3"
delta_sigma   = 36.5
eta           = 0.0

[compound.compound_2.R2]
"16.4"  = [0.62, 2.40]
"11.75" = [0.58, 1.75]

[compound.compound_8]
fluorine_type = "CF"
delta_sigma   = 70.8
eta           = 1.03

[compound.compound_8.R2]
"16.4"  = [0.55, 5.30]
"11.75" = [0.52, 3.20]

# ============================================================
# FastCSAR example — replace the [workflow] block above with:
# ============================================================
# [workflow]
# name           = "fastcsar"
# nucleus        = "19F"
# tau_c          = 1.0e-8
# protein_MW_kDa = 23.0
# B              = 16.4
# t_short        = 0.005    # 5 ms
# t_long         = 0.200    # 200 ms (CF3) or 0.100 for CF
# plot_output    = "ranking_fast.png"
#
# Compounds need only a single-field R2 entry:
# [compound.compound_1.R2]
# "16.4" = [0.65, 2.95]

# ============================================================
# Reporter assay example
# ============================================================
# [workflow]
# name           = "reporter"
# plot_output    = "ranking_reporter.png"
#
# [reporter]
# name           = "compound_1"
# signal_free    = 1.000
# signal_protein = 0.198
#
# [compound.compound_2]
# fluorine_type        = "CF3"
# delta_sigma          = 36.5
# eta                  = 0.0
# reporter_signal_plus = 0.45   # reporter signal with this compound present

# ============================================================
# Titration example
# ============================================================
# [workflow]
# name                   = "titration"
# nucleus                = "19F"
# tau_c                  = 1.0e-8
# protein_MW_kDa         = 23.0
# B                      = 16.4
# ligand_concentration   = 200.0              # µM
# protein_concentrations = [0, 5, 10, 20, 40, 60, 80]  # µM
# fit_KD                 = false
# plot_output            = "ranking_titration.png"
#
# For titration, the R2 value is a list with one entry per [P]:
# [compound.compound_1]
# fluorine_type = "CF3"
# delta_sigma   = 36.7
# eta           = 0.0
#
# [compound.compound_1.R2]
# "16.4" = [0.65, 0.80, 0.98, 1.40, 2.10, 2.60, 2.95]
"""


def write_example_config(path: str = "example_config.toml") -> None:
    """Write an example configuration file to disk."""
    with open(path, "w") as fh:
        fh.write(EXAMPLE_TOML)
    print(f"[config] Example config written to {path}")


# ============================================================================
# CLI entry point
# ============================================================================

if __name__ == "__main__":
    if len(sys.argv) < 2:
        write_example_config()
        print("Run:  python csar_workflows.py example_config.toml")
    else:
        run_from_config(sys.argv[1])
